routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\DesafioController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/desafio1/{id?}', [DesafioController::class, 'desafio1'])->name('desafio1');
Route::get('/desafio3/{id?}', [DesafioController::class, 'desafio3'])->name('desafio3');
Route::get('/desafio3_nuevo/{id}', [DesafioController::class, 'desafio3_nuevo'])->name('desafio3_nuevo');

Route::prefix('desafio5')->name('desafio5.')->middleware('auth')->group(function () {
    Route::view('tasks', 'livewire.tasks.index')->name('tasks');
    Route::view('logs/{id}', 'livewire.logs.index')->name('logs');
});

//Route Hooks - Do not delete//

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $table = 'tasks';

    protected $fillable = ['title','description','user_id','maximo'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function logs()
    {
        return $this->hasMany('App\Models\Log', 'task_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }
}

app/Http/Livewire/Logs.php
<?php

namespace App\Http\Livewire;

use App\Models\Task;
use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Log;
use Auth;

class Logs extends Component
{
    use WithPagination;

	protected $paginationTheme = 'bootstrap';
    public $selected_id, $keyWord, $comentario, $task_id, $user_id, $registrado;
    public $updateMode = false;
    public $task_selected, $task;

    public function mount()
    {
        $this->task_selected = request()->id;
        $this->task = Task::find(request()->id);
    }
    public function render()
    {
		$keyWord = '%'.$this->keyWord .'%';
        return view('livewire.logs.view', [
            'logs' => Log::where('user_id', Auth::user()->id)
                ->where('task_id', $this->task_selected)
                ->where(function ($q) use ($keyWord){
                    $q->orWhere('comentario', 'LIKE', $keyWord);
                })
                ->paginate(10),
        ]);
    }

    public function cancel()
    {
        $this->resetInput();
        $this->updateMode = false;
    }

    private function resetInput()
    {
		$this->comentario = null;
		$this->task_id = null;
		$this->user_id = null;
		$this->registrado = null;
    }

    public function store()
    {
        $this->validate([
		    'comentario' => 'required'
        ]);

        Log::create([
			'comentario' => $this-> comentario,
			'task_id' => $this->task_selected,
			'user_id' => Auth::user()->id,
			'registrado' => date('Y-m-d')
        ]);

        $this->resetInput();
		$this->emit('closeModal');
		session()->flash('message', 'Log registrado correctamente.');
    }

    public function edit($id)
    {
        $record = Log::findOrFail($id);

        $this->selected_id = $id;
		$this->comentario = $record-> comentario;
		$this->task_id = $record-> task_id;
		$this->user_id = $record-> user_id;
		$this->registrado = $record-> registrado;

        $this->updateMode = true;
    }

    public function update()
    {
        $this->validate([
		'comentario' => 'required',
		'task_id' => 'required',
		'user_id' => 'required',
		'registrado' => 'required',
        ]);

        if ($this->selected_id) {
			$record = Log::find($this->selected_id);
            $record->update([
			'comentario' => $this-> comentario,
			'task_id' => $this-> task_id,
			'user_id' => $this-> user_id,
			'registrado' => $this-> registrado
            ]);

            $this->resetInput();
            $this->updateMode = false;
			session()->flash('message', 'Log actualizado correctamente.');
        }
    }

    public function destroy($id)
    {
        if ($id) {
            $record = Log::where('id', $id);
            $record->delete();
        }
    }
}

app/Http/Livewire/Tasks.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Task;
use Auth;

class Tasks extends Component
{
    use WithPagination;

	protected $paginationTheme = 'bootstrap';
    public $selected_id, $keyWord, $title, $description, $user_id, $maximo;
    public $updateMode = false;
    public $users;

    public function mount()
    {
        $this->users = User::all();
    }

    public function render()
    {
		$keyWord = '%'.$this->keyWord .'%';
        return view('livewire.tasks.view', [
            'tasks' => Task::where('user_id', Auth::user()->id)
                ->where(function ($q) use ($keyWord){
                    $q->orWhere('title', 'LIKE', $keyWord)
                        ->orWhere('description', 'LIKE', $keyWord);
                })
                ->paginate(10),
        ]);
    }

    public function cancel()
    {
        $this->resetInput();
        $this->updateMode = false;
    }

    private function resetInput()
    {
		$this->title = null;
		$this->description = null;
		$this->user_id = null;
		$this->maximo = null;
    }

    public function store()
    {
        $this->validate([
            'title' => 'required',
            'description' => 'required',
            'user_id' => 'required',
            'maximo' => 'required',
        ]);

        Task::create([
			'title' => $this-> title,
			'description' => $this-> description,
			'user_id' => $this-> user_id,
			'maximo' => $this-> maximo
        ]);

        $this->resetInput();
		$this->emit('closeModal');
		session()->flash('message', 'Tarea registrada correctamente.');
    }

    public function edit($id)
    {
        $record = Task::findOrFail($id);

        $this->selected_id = $id;
		$this->title = $record-> title;
		$this->description = $record-> description;
		$this->user_id = $record-> user_id;
		$this->maximo = $record-> maximo;

        $this->updateMode = true;
    }

    public function update()
    {
        $this->validate([
		'title' => 'required',
		'description' => 'required',
		'user_id' => 'required',
		'maximo' => 'required',
        ]);

        if ($this->selected_id) {
			$record = Task::find($this->selected_id);
            $record->update([
			'title' => $this-> title,
			'description' => $this-> description,
			'user_id' => $this-> user_id,
			'maximo' => $this-> maximo
            ]);

            $this->resetInput();
            $this->updateMode = false;
			session()->flash('message', 'Tarea actualizada correctamente.');
        }
    }

    public function destroy($id)
    {
        if ($id) {
            $record = Task::where('id', $id);
            $record->delete();
        }
    }
}

resources/views/livewire/tasks/create.blade.php
<!-- Modal -->
<div wire:ignore.self class="modal fade" id="createDataModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="createDataModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createDataModalLabel">Nueva Tarea</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true close-btn">×</span>
                </button>
            </div>
           <div class="modal-body">
				<form>
                    <div class="form-group">
                        <label for="title">Título: </label>
                        <input wire:model="title" type="text" class="form-control" id="title">
                        @error('title') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="description">Descripción: </label>
                        <textarea wire:model="description" class="form-control" id="description" rows="3"></textarea>
                        @error('description') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="user_id">Usuario Asignado:</label>
                        <select wire:model="user_id" class="form-control" id="user_id">
                            <option value="0">-- Seleccione --</option>
                            @foreach($users as $user)
                                <option value="{{ $user->id }}">{{ $user->name }}</option>
                            @endforeach
                        </select>
                        @error('user_id') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="maximo">Fecha Máxima:</label>
                        <input wire:model="maximo" type="date" class="form-control" id="maximo" placeholder="Maximo">
                        @error('maximo') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary close-btn" data-dismiss="modal">Cancelar</button>
                <button type="button" wire:click.prevent="store()" class="btn btn-primary close-modal">Registrar</button>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/tasks/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @livewire('tasks')
        </div>
    </div>
</div>
@endsection

resources/views/livewire/tasks/update.blade.php
<!-- Modal -->
<div wire:ignore.self class="modal fade" id="updateModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
       <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabel">Actualizar Tarea</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span wire:click.prevent="cancel()" aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
					<input type="hidden" wire:model="selected_id">
                    <div class="form-group">
                        <label for="title">Título: </label>
                        <input wire:model="title" type="text" class="form-control" id="title">
                        @error('title') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="description">Descripción: </label>
                        <textarea wire:model="description" class="form-control" id="description" rows="3"></textarea>
                        @error('description') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="user_id">Usuario Asignado:</label>
                        <select wire:model="user_id" class="form-control" id="user_id">
                            <option value="0">-- Seleccione --</option>
                            @foreach($users as $user)
                                <option value="{{ $user->id }}">{{ $user->name }}</option>
                            @endforeach
                        </select>
                        @error('user_id') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="maximo">Fecha Máxima:</label>
                        <input wire:model="maximo" type="date" class="form-control" id="maximo" placeholder="Maximo">
                        @error('maximo') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" wire:click.prevent="cancel()" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" wire:click.prevent="update()" class="btn btn-primary" data-dismiss="modal">Actualizar</button>
            </div>
       </div>
    </div>
</div>

resources/views/livewire/tasks/view.blade.php
@section('title', __('Mis Tareas'))
			<div class="card">
				<div class="card-header">
					<div style="display: flex; justify-content: space-between; align-items: center;">
						<div class="float-left">
							<h4>Mis Tareas</h4>
						</div>
						@if (session()->has('message'))
						<div wire:poll.4s class="btn btn-sm btn-success" style="margin-top:0px; margin-bottom:0px;"> {{ session('message') }} </div>
						@endif
						<div>
							<input wire:model='keyWord' type="text" class="form-control" name="search" id="search" placeholder="Buscar">
						</div>
						<div class="btn btn-sm btn-primary" data-toggle="modal" data-target="#createDataModal">
                            Nueva Tarea
						</div>
					</div>
				</div>

				<div class="card-body">
						@include('livewire.tasks.create')
						@include('livewire.tasks.update')
				<div class="table-responsive">
					<table class="table table-bordered table-sm">
						<thead class="thead">
							<tr>
								<th>ID</th>
								<th>Título</th>
								<th>Descripción</th>
								<th>Asignado</th>
								<th>Fecha Máxima</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							@foreach($tasks as $row)
							<tr class="{{ (strtotime($row->maximo) < strtotime(date("d-m-Y")))?'table-danger':'' }}">
								<td>{{ $row->id }}</td>
								<td>{{ $row->title }}</td>
								<td>{{ $row->description }}</td>
								<td>{{ $row->user->name }}</td>
								<td>{{ $row->maximo }}</td>
								<td width="120">
                                    <div class="btn-group">
                                        <a href="{{ route('desafio5.logs', $row->id) }}" class="btn btn-outline-danger btn-sm">
                                            <i class="fa fa-list"></i>
                                        </a>
                                    </div>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-outline-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-cogs"></i>
                                        </button>
                                        <div class="dropdown-menu dropdown-menu-right">
                                        <a data-toggle="modal" data-target="#updateModal" class="dropdown-item" wire:click="edit({{$row->id}})">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                        <a class="dropdown-item" onclick="confirm('¿Eliminar Tarea?\nNo podrá recuperarla posterriormente!')||event.stopImmediatePropagation()" wire:click="destroy({{$row->id}})"><i class="fa fa-trash"></i> Eliminar</a>
                                        </div>
                                    </div>
								</td>
							@endforeach
						</tbody>
					</table>
					{{ $tasks->links() }}
					</div>
				</div>
			</div>